//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsLibrary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnimalDefinitions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalDefinitions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalsApplication.AnimalDefinitions", typeof(AnimalDefinitions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Птицы (лат. Aves) — группа теплокровных яйцекладущих позвоночных животных, традиционно рассматриваемая в ранге отдельного класса. Хорошо обособлена от остальных групп современных животных. Один из наиболее характерных признаков — покров из перьев, предохраняющий тело от неблагоприятных изменений температуры и играющий важную роль при полёте. Способность к полёту — важнейшая особенность птиц (отсутствие её у некоторых видов — вторичное явление). Передние конечности приобрели форму крыльев. Птицы обладают осо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BirdDef {
            get {
                return ResourceManager.GetString("BirdDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рыбы (лат. Pisces) — обширная группа водных челюстноротых позвоночных животных, ранее считавшаяся надклассом. Рыбы характеризуются жаберным дыханием на всех этапах постэмбрионального развития организма..
        /// </summary>
        internal static string FishDef {
            get {
                return ResourceManager.GetString("FishDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Млекопитающие (лат. Mammalia) — класс позвоночных животных, основной отличительной особенностью которых является вскармливание детёнышей молоком. Класс входит в кладу синапсид надкласса четвероногих. По подсчётам биологов, известно более 6400 современных видов млекопитающих, среди которых и вид Человек разумный (лат. Homo sapiens); общее же число видов млекопитающих, включая вымершие, превышает 20 000..
        /// </summary>
        internal static string MammalDef {
            get {
                return ResourceManager.GetString("MammalDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пресмыкающиеся, или репти́лии (лат. Reptilia), — традиционно выделяемый класс преимущественно наземных позвоночных животных из клады амниот, включающий современных черепах, крокодилов, клювоголовых и чешуйчатых. Пресмыкающиеся являются парафилетической группой, так как дали начало птицам, но не включают их самих. В качестве монофилетической альтернативы класса выделяется клада завропсид, или рептилий в пересмотренном составе, в которую включают представителей традиционного класса пресмыкающихся (кроме зверо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ReptileDef {
            get {
                return ResourceManager.GetString("ReptileDef", resourceCulture);
            }
        }
    }
}
